// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.34209
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

#region Designer generated code

using TechTalk.SpecFlow;

#pragma warning disable

namespace Selkie.Services.Aco.Specflow
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("ServiceAco")]
    public partial class ServiceAcoFeature
    {
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }

        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }

        private static TechTalk.SpecFlow.ITestRunner testRunner;

        [NUnit.Framework.OneTimeSetUpAttribute]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            var featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"),
                                                                "ServiceAco",
                                                                "",
                                                                ProgrammingLanguage.CSharp,
                                                                ( ( string[] ) ( null ) ));
            testRunner.OnFeatureStart(featureInfo);
        }

        [NUnit.Framework.OneTimeTearDownAttribute]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }

        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }

        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }

        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Colony sends BestTrailMessage")]
        public virtual void ColonySendsBestTrailMessage()
        {
            var scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Colony sends BestTrailMessage",
                                                                  ( ( string[] ) ( null ) ));
#line 36
            this.ScenarioSetup(scenarioInfo);
#line 37
            testRunner.Given("Service is running and colony created",
                             ( ( string ) ( null ) ),
                             ( ( TechTalk.SpecFlow.Table ) ( null ) ),
                             "Given ");
#line 38
            testRunner.And("Did not a receive a BestTrailMessage",
                           ( ( string ) ( null ) ),
                           ( ( TechTalk.SpecFlow.Table ) ( null ) ),
                           "And ");
#line 39
            testRunner.Then("the result should be that I received a BestTrailMessage",
                            ( ( string ) ( null ) ),
                            ( ( TechTalk.SpecFlow.Table ) ( null ) ),
                            "Then ");
#line hidden
            this.ScenarioCleanup();
        }

        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Colony sends FinishedMessage")]
        public virtual void ColonySendsFinishedMessage()
        {
            var scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Colony sends FinishedMessage",
                                                                  ( ( string[] ) ( null ) ));
#line 41
            this.ScenarioSetup(scenarioInfo);
#line 42
            testRunner.Given("Service is running and colony created",
                             ( ( string ) ( null ) ),
                             ( ( TechTalk.SpecFlow.Table ) ( null ) ),
                             "Given ");
#line 43
            testRunner.And("Did not a receive a FinishedMessage",
                           ( ( string ) ( null ) ),
                           ( ( TechTalk.SpecFlow.Table ) ( null ) ),
                           "And ");
#line 44
            testRunner.Then("the result should be that I received a FinishedMessage",
                            ( ( string ) ( null ) ),
                            ( ( TechTalk.SpecFlow.Table ) ( null ) ),
                            "Then ");
#line hidden
            this.ScenarioCleanup();
        }

        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("CreateColony message request and response")]
        public virtual void CreateColonyMessageRequestAndResponse()
        {
            var scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("CreateColony message request and response",
                                                                  ( ( string[] ) ( null ) ));
#line 24
            this.ScenarioSetup(scenarioInfo);
#line 25
            testRunner.Given("Service is running",
                             ( ( string ) ( null ) ),
                             ( ( TechTalk.SpecFlow.Table ) ( null ) ),
                             "Given ");
#line 26
            testRunner.And("Did not a receive a CreatedColonyMessage",
                           ( ( string ) ( null ) ),
                           ( ( TechTalk.SpecFlow.Table ) ( null ) ),
                           "And ");
#line 27
            testRunner.When("I send a CreateColonyMessage",
                            ( ( string ) ( null ) ),
                            ( ( TechTalk.SpecFlow.Table ) ( null ) ),
                            "When ");
#line 28
            testRunner.Then("the result should be that I received a CreatedColonyMessage",
                            ( ( string ) ( null ) ),
                            ( ( TechTalk.SpecFlow.Table ) ( null ) ),
                            "Then ");
#line hidden
            this.ScenarioCleanup();
        }

        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Ping AcoService")]
        public virtual void PingAcoService()
        {
            var scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Ping AcoService",
                                                                  ( ( string[] ) ( null ) ));
#line 3
            this.ScenarioSetup(scenarioInfo);
#line 4
            testRunner.Given("Service is running",
                             ( ( string ) ( null ) ),
                             ( ( TechTalk.SpecFlow.Table ) ( null ) ),
                             "Given ");
#line 5
            testRunner.And("Did not receive ping response message",
                           ( ( string ) ( null ) ),
                           ( ( TechTalk.SpecFlow.Table ) ( null ) ),
                           "And ");
#line 6
            testRunner.When("I send a ping message",
                            ( ( string ) ( null ) ),
                            ( ( TechTalk.SpecFlow.Table ) ( null ) ),
                            "When ");
#line 7
            testRunner.Then("the result should be a ping response message",
                            ( ( string ) ( null ) ),
                            ( ( TechTalk.SpecFlow.Table ) ( null ) ),
                            "Then ");
#line hidden
            this.ScenarioCleanup();
        }

        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Start colony message request and response")]
        public virtual void StartColonyMessageRequestAndResponse()
        {
            var scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Start colony message request and response",
                                                                  ( ( string[] ) ( null ) ));
#line 30
            this.ScenarioSetup(scenarioInfo);
#line 31
            testRunner.Given("Service is running and colony created",
                             ( ( string ) ( null ) ),
                             ( ( TechTalk.SpecFlow.Table ) ( null ) ),
                             "Given ");
#line 32
            testRunner.And("Did not a receive a StartedMessage",
                           ( ( string ) ( null ) ),
                           ( ( TechTalk.SpecFlow.Table ) ( null ) ),
                           "And ");
#line 33
            testRunner.When("I send a StartMessage",
                            ( ( string ) ( null ) ),
                            ( ( TechTalk.SpecFlow.Table ) ( null ) ),
                            "When ");
#line 34
            testRunner.Then("the result should be that I received a StartedMessage",
                            ( ( string ) ( null ) ),
                            ( ( TechTalk.SpecFlow.Table ) ( null ) ),
                            "Then ");
#line hidden
            this.ScenarioCleanup();
        }

        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Started AcoService sends message")]
        public virtual void StartedAcoServiceSendsMessage()
        {
            var scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Started AcoService sends message",
                                                                  ( ( string[] ) ( null ) ));
#line 20
            this.ScenarioSetup(scenarioInfo);
#line 21
            testRunner.Given("Service is running",
                             ( ( string ) ( null ) ),
                             ( ( TechTalk.SpecFlow.Table ) ( null ) ),
                             "Given ");
#line 22
            testRunner.Then("the result should be that I received a ServiceStartedMessage",
                            ( ( string ) ( null ) ),
                            ( ( TechTalk.SpecFlow.Table ) ( null ) ),
                            "Then ");
#line hidden
            this.ScenarioCleanup();
        }

        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Stop AcoService")]
        public virtual void StopAcoService()
        {
            var scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Stop AcoService",
                                                                  ( ( string[] ) ( null ) ));
#line 9
            this.ScenarioSetup(scenarioInfo);
#line 10
            testRunner.Given("Service is running",
                             ( ( string ) ( null ) ),
                             ( ( TechTalk.SpecFlow.Table ) ( null ) ),
                             "Given ");
#line 11
            testRunner.And("Did not receive ping response message",
                           ( ( string ) ( null ) ),
                           ( ( TechTalk.SpecFlow.Table ) ( null ) ),
                           "And ");
#line 12
            testRunner.When("I send a stop message",
                            ( ( string ) ( null ) ),
                            ( ( TechTalk.SpecFlow.Table ) ( null ) ),
                            "When ");
#line 13
            testRunner.Then("the result should be service not running",
                            ( ( string ) ( null ) ),
                            ( ( TechTalk.SpecFlow.Table ) ( null ) ),
                            "Then ");
#line hidden
            this.ScenarioCleanup();
        }

        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Stopping AcoService sends message")]
        public virtual void StoppingAcoServiceSendsMessage()
        {
            var scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Stopping AcoService sends message",
                                                                  ( ( string[] ) ( null ) ));
#line 15
            this.ScenarioSetup(scenarioInfo);
#line 16
            testRunner.Given("Service is running",
                             ( ( string ) ( null ) ),
                             ( ( TechTalk.SpecFlow.Table ) ( null ) ),
                             "Given ");
#line 17
            testRunner.When("I send a stop message",
                            ( ( string ) ( null ) ),
                            ( ( TechTalk.SpecFlow.Table ) ( null ) ),
                            "When ");
#line 18
            testRunner.Then("the result should be that I received a ServiceStoppedMessage",
                            ( ( string ) ( null ) ),
                            ( ( TechTalk.SpecFlow.Table ) ( null ) ),
                            "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}

#pragma warning restore

#endregion